### ISSUE TITLE
阅读论文的一些困惑

### ISSUE THREAD

**Issue by 2460707925** [WeijieMax/LSSInst#2]
![image](https://github.com/user-attachments/assets/74a27234-d6ae-4e23-b956-ae1388efd7cf)
1.Pvel这里面这个速度的补偿是不是有点问题，咱们已知的ego速度信息是3D域的，但是你这边的公式看起来是2D图像域的，所以这比边这个Pvel是3D的还是2D的
2.Spatiotemporal Sampling and Fusion 你这边时空融合中，时间融合这个论文里输入是不是少了？因为从论文看来你这边输入的只有当前帧的instance query，那么都没有历史instance query ，在哪里进行时间的补偿？
3.最后迭代生成box的公式能更加详细一点嘛，从论文来看就是得到所有历史帧对应的feature,然后迭代到原始的feature中并预测offset,最终将所有的offset 累积到第一阶段的box中，这个过程虽然很简单但也存在一些困惑，比如你这个只回归x,y,z，还是l,w,h...等其他参数都是这样回归的。

**Comment by WeijieMax** [comment]
首先感谢提问与关注~
1.我check了一下，这边公式确实写的有点歧义，非常感谢指出。P_vel就是3D域的速度，实际上我们在代码中是先将3D点坐标补偿了之后再投影到图像2D域上的。公式这里应该用的是p_vel from warping P_vel as the same. 我会在文章的后续版本中更新一下。
2.历史instance query是当前的query分别去各个历史的img feature中去采出来的，然后通过时序的encoder融合成回顾过历史的updated query (可见公式6)
3.我们在公式4上面的文字其实提到了P_box包含了所有的3D检测属性，都是需要做回归的。

**Comment by 2460707925** [comment]
谢谢回答，第二个没看到Fimg是包含历史的图像了。
